### ISSUE TITLE
Define Non-Typography Content Margin/Flow Patterns

### ISSUE THREAD

**Issue by blzaugg** [liferay/lexicon-site#200]
### Key

- Blue: Paragraph Margins
- Green: Good Pattern
- Red: Bad Pattern

![content-images](https://user-images.githubusercontent.com/1626739/53677873-e2750d80-3c6b-11e9-9e11-24de9783e7d0.png)

**Comment by pat270** [comment]
@blzaugg do you want some kind of utility classes + markup pattern to add on the image/p tag to achieve the green example?

**Comment by blzaugg** [comment]
For Lexicon, I want a design/pattern to follow. I could not find any.

For Clay I'd want at least one "wrapping" class. I'm already working on creating 2 "wrapping" classes: an "styled content editor" class and a "styled content display" class; in Portal Themes. This could be applied at the Clay level, but I'm still working that out.

The classes wouldn't provide styles themselves, but would allow better targeting of child content elements. I don't think utility classes on the child content elements themselves is practical, as we may not have control over the markup used in the editor or its output.

I planned something like so, for targeting styled content:
```scss
.style-content-display,
.style-content-editor {
    img {
        max-width: 100%;

        &[style*="float"] {
	    margin: 1rem;
        }

        &[style*="float: left;"],
        &[style*="float:left;"] {
	    margin-left: 0;
        }
    }

    p {
        margin: 1rem 0;
    }
}

// So we can target editor vs content independently
.style-content-editor {
    img {
        border: 2px dashed blue;
    }
}
```

We are already doing this in Portal but it's [messy](https://github.com/jonmak08/liferay-portal/blob/28616fec43baf1d6689fb756378acf9c08cf3aec/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/common_main.scss#L65-L78), [fragile](https://github.com/jonmak08/liferay-portal/blob/28616fec43baf1d6689fb756378acf9c08cf3aec/modules/apps/journal/journal-content-web/src/main/resources/META-INF/resources/css/main.scss#L3-L18) and [inconsistent](https://github.com/jonmak08/liferay-portal/blob/28616fec43baf1d6689fb756378acf9c08cf3aec/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/main.scss#L5-L20). I want to centralize/standardize it.
